jpmobile/jpmobile

lib/jpmobile/mail.rb, lib/jpmobile/util.rb, spec/unit/email-fixtures/docomo-decomail.eml, spec/unit/email-fixtures/iphone-unicode-emoji.eml, spec/unit/receive_mail_spec.rb, spec/unit/util_spec.rb
UTF-8絵文字と特定の記号を同時に含むメールの受信時にEncoding::InvalidByteSequenceErrorが発生しておりまして、原因を追ったところ`NKF.guess`がエンコーディング判定に失敗しているためと判明しました。
```irb
1.9.3-p545 :002 > NKF.guess "\u{1F384}\u2763"
=> #<Encoding:ASCII-8BIT>
```
この`NKF.guess`して`Jpmobile::Util.correct_encoding`する一連の流れはもともと c556e9aa8a42622e25b8ffd3bcfd55512d1c6d88 で導入されており、その時の[convert_encoding_jpmobile](https://github.com/jpmobile/jpmobile/blob/c556e9aa8a42622e25b8ffd3bcfd55512d1c6d88/lib/jpmobile/mail.rb#L236)の実装では`subject_charset`をメール全体のcharsetとみなしていたため、SubjectとBodyのエンコーディングが異なる場合にうまく対応できず、その回避策としてBodyのエンコーディングをNKF.guessにより判別しそれっぽく処理する実装になっていたものと考えられます。
ただ、#70 のPull Requestによりsubject_charsetとBodyのcharsetを個別に扱えるよう変更が加わっていますので、このfailsafe procedureはもはや不要なはずです。逆に誤検出による問題が出てきてしまうため、この処理を取り除き、#84 …
=> NKF.guessが特定のUTF-8文字列についてEncoding:ASCII-8BITを返す問題に対応

lib/jpmobile/mail.rb, lib/jpmobile/util.rb, spec/unit/email-fixtures/iphone-circled-numbers-in-jis.eml, spec/unit/receive_mail_spec.rb
#83 とも関連するのですが、入れてくるのは半角カナだけではなく丸数字`①`などのCP50220文字をも含むことが判明しました。そのためISO-2022-JPでcharset変換に失敗した際は無条件にCP50220でリトライするようにしています。
また、それに伴いSubjectのcharset変換の流れを見直しました。
現状では絵文字入りのBエンコードされたSubjectを処理する際
1. mail gem側で`Mail::Ruby19.b_value_decode`を呼ぶ
2. 絵文字の処理には機種特有の処理が必要なので、1は失敗。[rescueして](https://github.com/jpmobile/jpmobile/blob/341114dddf12dfc306efb01942ed1246372b2ffd/lib/jpmobile/mail.rb#L14)ASCII-8BITの状態で返す
3. 2で返されたASCII-8BIT文字列を[`convert_encoding_jpmobile`](https://github.com/jpmobile/jpmobile/blob/341114dddf12dfc306efb01942ed1246372b2ffd/lib/jpmobile/mail.rb#L257-268)内で機種特有の処理を`@mobile`インスタンスにまかせつつcharset変換
の流れとなっていますが、この1でわざわざ失敗するのは無意味で、最初から機種特有の知識をもって変換すれば１回で済むと考えました。
そのため`Mail::SubjectField`クラスにて`@mobile`インスタンスを受け取り、Bエンコーディングのデコードを行ってしまう流れに変更してあります。
=> iPhone mailerがISO-2022-JPのメールにCP50220文字を入れてくる問題への対応

CONTRIBUTING.md
`rake test`でテストを実行した際、smtpdが動いていない場合、
以下の様に一部のテストが失敗します。
```
~/Projects/jpmobile
$ rake test                                                                                                                                                                                              master ca7a770
/Users/tomoya/.anyenv/envs/rbenv/versions/2.2.0/bin/ruby -I/Users/tomoya/.anyenv/envs/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib:/Users/tomoya/.anyenv/envs/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/lib /Users/tomoya/.anyenv/envs/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.1/exe/rspec --pattern spec/unit/\*\*/\*_spec.rb
Run options:
include {:focus=>true}
exclude {:broken=>true}
All examples were filtered out; ignoring {:focus=>true} …
```
=> Add a description about smtpd mock in test

jpmobile.gemspec
bundlerの1.10.xだと
```
gem.add_dependency 'rails', '~> 4.1.0'
````
と
```
gem.add_development_dependency 'rails'
```
が両方存在するとrailsでjpmobileの読み込みに失敗します。
というわけで、add_development_dependencyを削除しました。
=> deleted development dependency on rails to avoid latest bundler error

lib/jpmobile/resolver.rb
For rails 4.2.5.1, this patch applies security fix with the same way as upstream: https://github.com/rails/rails/compare/v4.2.5...v4.2.5.1
=> Apply reject_files_external_to_app

lib/jpmobile/filter.rb
Ruby 2.3.0の```frozen-string-literal```を使っていると、```force_encoding```でcan't modify frozen Stringのエラーになります。```clone```ではなく```dup```すればfrozenは解除されます。
このパッチでviewの表示が通ることは確認しました。
=> frozen-string-literalへの対応

lib/jpmobile/resolver.rb
RailsのActionPack Variants使用時に、 `Jpmobile::Resolver`がテンプレート解決に使われると
正しくViewが選ばれない問題を修正しました。
現在の `Jpmobile::Resolver`の記述では `request.variant`に値を指定しても、
テンプレートパスの生成パターンに`variant`を当てはめる箇所が無いため、
`index.html+hoge.erb` のテンプレートを選ばずに `index.html.erb`が選ばれます。
=> Add variant param to pattern for detecting template

lib/jpmobile/trans_sid.rb
`session.inspect` in Rails3 had read session data.
https://github.com/rails/rails/blob/3-0-stable/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L89
However It doesn't load session data now.
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/request/session.rb#L174
=> session.inspect is meaningless.

lib/jpmobile/util.rb, spec/unit/util_spec.rb
#119 と似た問題なのですが、Rails 5.0.0を使ってcontroller specでパラメータにfrozen Stringが入っているとこけました。
（ブラウザから動かしたときにどうなるかは、まだ試してません。）
テストも追加してあります。
p.s. Rails 5 は Ruby >= 2.2 ですし、`respond_to?(:force_encoding)` はもう要らないように思うのですがどうでしょう？　暇をみてパッチを作ってもいいかなあと。
=> frozen string への対応

jpmobile.gemspec
https://rubygems.org/gems/jpmobile の LICENSES への記載や、`bundle licenses` での一覧表示などに使われています。適用されているライセンスについて利用者が知る機会が増えるため、次回以降のリリースに向けて指定しておくと良いと考えました。
=> Specify license to gemspec

CONTRIBUTING.md, lib/jpmobile/filter.rb, test/rails/overrides/spec/controllers/hankaku_filter_controller_spec.rb
以前は再帰処理を行っていましたが、変更後に再帰処理が正しく動いておりません。
その修正です:bow:
https://github.com/jpmobile/jpmobile/commit/c7217a47b488e004045f252b698676a1f9c189b5#diff-f7d03412694f6e798d8ca433fa776fe9
この時から、うまく動かなくなっていると思います。
```ruby
params = { x : [1, 2] }
この時に再帰処理でparams[k]が`Enumrable`にならない時に落ちます。
```
=> convert_parametersで再帰処理が動いていない

lib/jpmobile/rack/filter.rb, test/rails/overrides/spec/requests/pc_spec.rb
開発ありがとうございます！ 🙏 
routesが存在しない場合、 `env['Content-Type']` がnilになるため下記のエラーが発生しました
```
1) PCからのアクセスの場合 routesが存在しない場合 ActionController::RoutingErrorをraiseする
Failure/Error: expect { get '/not_exist', params: {}, env: @headers }.to raise_error ActionController::RoutingError
expected ActionController::RoutingError, got #<NoMethodError: undefined method `match?' for nil:NilClass> with backtrace:
```
おそらく以前だと、 
```ruby
nil =~ %r{text/html|application/xhtml\+xml} # => nil
``` 
となっていたため問題は起きなかったようです。
https://github.com/jpmobile/jpmobile/blob/8960e0c9411a33b8b2409afb78c1442671b39810/lib/jpmobile/rack/filter.rb#L16
- Ruby 2.4.4
- Rails 5.2.0
以前と同様にnilの場合も対応するようにしました。ご確認お願いします :eyes:
=> routesが存在しない場合、ActionController::RoutingErrorがraiseされない

lib/jpmobile/hook_action_view.rb, lib/jpmobile/rails.rb
Jpmobile keeps an ancient copy of `html_options_for_form` method but this is quite a dangerous approach for extending an existing method, and in fact Jpmobile has been failing to catch up the upstream changes (our version misses this part https://github.com/rails/rails/blob/7351ccdb880ca4b69d24b2615019ed902652f45e/actionview/lib/action_view/helpers/form_tag_helper.rb#L836-L844 ).
Actually, the Ruby interpreper warns against this method redefinition as follows:
`warning: method redefined; discarding old html_options_for_form`.
This patch fixes these problems by switching the monkey-patch approach to call the framework original verision + inject our own option using Module#prepend.
=> Prefer Module#prepend + super over open-classing for extending html_options_for_form

lib/jpmobile/rack/params_filter.rb
Pumaを使って運用しているアプリケーションでたまに発生していたエラーの調査を行ったところ
ParamsFilterがThreadベースのサーバでの利用を想定されていないようであったので修正を行いました。
そして出来れば最新だけでなく修正された4.2系もリリースを期待しております 🙇
=> Change ParamsFilter to threadsafe

lib/jpmobile/resolver.rb
`include Jpmobile::ViewSelector` をしているところで、以下のようなエラーが出るようになってしまいました。
```
NameError:
uninitialized constant Jpmobile::ActionView::FileSystemResolver
```
https://github.com/jpmobile/jpmobile/pull/149 で `module Jpmobile::ActionView` が入ったのでそれが原因かなと思い修正しました。
=> fix NameError

lib/jpmobile/view_selector.rb
Follow https://github.com/jpmobile/jpmobile/commit/39155df128b70d55ecc477bf35d4bd25429de20f.
This PR fixes the following `LoadError` when using Rails 6.1.
```console
class ApplicationController < ActionController::Base
include Jpmobile::ViewSelector
end
```
No errors.
```console
% bin/rails c
Running via Spring preloader in process 96658
Loading development environment (Rails 6.0.3.5)
irb(main):001:0> Jpmobile::ViewSelector
=> Jpmobile::ViewSelector
```
`LoadError` occors.
```console
% bin/rails c
Running via Spring preloader in process 91693
Loading development environment (Rails 6.1.3)
irb(main):001:0> Jpmobile::ViewSelector
Traceback (most recent call last):
1: from (irb):1
LoadError (cannot load such file -- jpmobile/view_selector)
```
Parhaps …
=> Fix `LoadError` when using Rails 6.1

lib/jpmobile/mobile/android_tablet.rb, spec/rack/jpmobile/mobile_by_ua_spec.rb
Android版Instagramのアプリ内ブラウザからアクセスした場合、デバイスの判定が必ずAndroid Tabletとなってしまう不具合を発見したので修正しました。
Android版Instagramのアプリ内ブラウザではUser Agentを「... Android ... Mobile ... Android ...」といった形で、`Android` という文字列が複数回入る形で設定します。
現状のjpmobileのAndroidTablet判定の正規表現だと、1回だけ `Android ... Mobile` とくるパターンはうまくタブレットでは無いと判定できるのですが、 2回目の `Android` という文字列が来てしまうと、必ずタブレットと判定してしまう状況でした。
そこで「 `Mobile` という文字列は含まず、 `Android` という文字列は含む」という正規表現に修正して、何度 `Android` という文字列が入っても `Mobile` という文字が入っている場合にはタブレットと判定しないように修正しました。
=> Fixed a bug that access from Instagram in-app browser for Android is falsely detected as via tablet

Gemfile.lock
Gemfile.lockのjpmobileのバージョンを更新します。
最新のバージョンで `bundle install` してみたところ、Gemfile.lockに変化がありました。
Gemfile.lockをGitで管理する場合、バージョンを上げるたびに `bundle install` を実行し、Gemfile.lockも同時に更新しないといけないはず。
現時点のGitHubのmainブランチの最新版で `bundle install` を実行することで、Gemfile.lockを更新しました。
過去のバージョン変更時にはどう対処していたのか調べてみました。
6.1.2では、バージョン変更とは別のcommitでGemfile.lockを更新している。
- https://github.com/jpmobile/jpmobile/commit/38cb52210a3bff332ac3d6d04614852746c76064
- https://github.com/jpmobile/jpmobile/commit/e1eb34304f15349741558f36f30a453305a6194e
6.1.1では、バージョン変更と同commitでGemfile.lockを更新している。
- https://github.com/jpmobile/jpmobile/commit/a12af34b6ce3428512e17d968e2700fa91e38509
6.1.0では、バージョン変更とは別のcommitでGemfile.lockを更新している。
- https://github.com/jpmobile/jpmobile/commit/2d7599da416f972556cbc2b2e627451f3a7ebc48
- …
=> Update jpmobile version from 6.1.2 to 7.0.0 in Gemfile.lock

lib/jpmobile/template_details.rb
To resolve https://github.com/jpmobile/jpmobile/issues/198.
テンプレート候補を優先度順に並び替える際、handler (erbやhaml等) より mobile (smart_phone等) の一致を優先するように変更します。
=> Change mobile template priority

Gemfile.lock
手元で `bundle install` を実行してみたところ、差分が生じたので、Gemfile.lockの変更漏れかと思いPull Requestを出しました。
https://github.com/jpmobile/jpmobile/pull/184 と同様の変更です。
=> Update jpmobile version from 7.0.1 to 7.0.2 in Gemfile.lock

.rubocop.yml, jpmobile.gemspec
gemspecのメタデータを幾らか改善したいのですが、どうでしょう？
- ホームページのURLをHTTPからHTTPSに変更しました
- 余計なリダイレクトを省けます
- ソースコードへのリンクを追加しました
- gemspecからソースコードの情報が得られなかったため
- https://rubygems.org/gems/jpmobile は多分サイト上で編集したのでリンクが表示されている
- 2018年末に編集機能は廃止されたので、もはや編集はできない
- つまり書くならgemspecに書いた方がいい
- ~~変更履歴へのリンクを追加しました~~
- jpmobileはCHANGELOG.mdを持っていないことが発覚したのでやめました
人間向けのインターフェースだと、https://rubygems.org/gems/jpmobile のこのへんに影響があります:
GitHubのリポジトリに登録されているウェブサイトもHTTPになってたので、これは手作業で変える必要があるかも。
=> Improve some URLs in gemspec

test/rails/overrides/Gemfile.jpmobile, test/rails/overrides/spec/system/filter_spec.rb, test/rails/overrides/spec/system_helper.rb
- activerecord_session-store の指定が古いために rackup が 1.0.1 になってしまっていたのでその指定の解除
- `Content-Type` ではなく `content-type` になってしまっていたので、大文字小文字どちらでも対応できるような暫定対応
=> Fix rackup incompatibility
