CONTRIBUTING.md
README.rdoc

jpmobileの開発に貢献したい開発者向けドキュメントが見受けられなかったので、私自身がつまづいた点を`CONTRIBUTING.md`にまとめました。

Add document to developer

---

test/rails/overrides/spec/requests/trans_sid_spec.rb

fix rails trans_sid redirect example

---

.rubocop.yml
lib/jpmobile/email.rb
lib/jpmobile/emoticon.rb
lib/jpmobile/mail.rb
lib/jpmobile/mobile/au.rb
lib/jpmobile/rack/filter.rb
lib/jpmobile/rack/params_filter.rb
lib/jpmobile/trans_sid.rb
lib/jpmobile/util.rb

Support Ruby 2.3

---

lib/jpmobile/rails.rb

My bad, the code here doesn't do what the commit comment means (seems like I forgot to rewrite what I copy & pasted from the code above...).

I said, "action_view has its own dedicated on_load hook"

---

lib/jpmobile/trans_sid.rb

Convert explicitly

---

README.md

I found some typos , and try to fix them. 👍
Best regards,
s4na

Fix markdown typo

---

.circleci/config.yml
Gemfile.lock
jpmobile.gemspec
lib/tasks/jpmobile_tasks.rake
test/rails/overrides/Gemfile.jpmobile
test/rails/overrides/spec/rails_helper.rb
test/rails/overrides/spec/requests/filter_spec.rb
test/rails/overrides/spec/requests/template_path_spec.rb
test/rails/overrides/spec/system/admin/top_spec.rb
test/rails/overrides/spec/system/filter_spec.rb
test/rails/overrides/spec/system/support/cuprite_setup.rb
test/rails/overrides/spec/system_helper.rb

Use cuprite

---

index.md

I fixed a command of clone the project in gh pages.

GitHub no longer supports unauthenticated git protocol

---

.circleci/config.yml
Gemfile.lock

https://github.com/jpmobile/jpmobile/pull/184#issuecomment-1010802985 でコメントした件をPull Requestにしてみました。

Make sure Gemfile.lock is up to date on CI

---

README.md

Use the same link as this [commit](https://github.com/D-system/jpmobile/commit/12b6f870ff8acab03256bba898880044422f2466#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R11)

Update GeoKit link

---

Gemfile.lock

bundle update --conservative nokogiti

---

lib/jpmobile/rails.rb

Include only in testing

---

Gemfile.lock
lib/jpmobile/mail.rb

Bumpup rubocops

---

.circleci/config.yml

Fix browser-tools error

---

Gemfile.lock
lib/jpmobile/mail.rb

Bumpup rubocop

---

Gemfile.lock
jpmobile.gemspec
lib/jpmobile/mail.rb

Bumpup mail

---

lib/jpmobile/request_with_mobile.rb

些細な変更です。
この並びで「viewの切り替えをするかどうか」というコメントは何かの間違いではないかと感じたので、
- mobile?
- tablet?
のコメントと同様の内容に変更しておくのはどうでしょうか。

Fix comment about `Jpmobile::RequestWithMobile#smart_phone?`

---

lib/tasks/jpmobile_tasks.rake

Fix handling rake task option

---

Gemfile.lock
jpmobile.gemspec

Updates for dependabot

---

.circleci/config.yml

Bump up circleci/browser-tools

---

Gemfile.lock

Bumpups from dependabot
